# ======================================
# Configuração do ImprimirPDF
# ======================================

# Nome EXATO da impressora instalada no Windows
IMPRESSORA=EPSON TM-T20X Receipt

# Nome do arquivo PDF localizado na mesma pasta
ARQUIVO=ESPELHO CAIXA 2 IMPRIMIR.pdf